server:
   port: 8095

spring:
  datasource:
    url: jdbc:mysql://insurance.cybe1ssjbczm.us-east-1.rds.amazonaws.com/insurance
    username: root
    password: adminadmin  
     
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect