server:
   port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Insurance_app
    username: root
    password: Root  
     
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect